---
title: "Exploración Plantas Extintas ClR2"
author: "Natalia Fierro Vásquez"
date: "07-09-2020"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(kableExtra)
```

## Introducción

### De donde vienen los datos

Estos datos provienen de la base de datos de Plantas Extintas de la **UICN**. Se obtuvieron desde [el siguiente repositorio](https://github.com/rfordatascience/tidytuesday) github 

```{r, echo = FALSE}
plants <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/plants.csv')
actions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/actions.csv')
threats <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/threats.csv')

```


## Datos de Sudamérica 

El número de especies que hay en Sudamérica que hay en la base de Plantas Extintas es de `r plants %>% dplyr::filter(continent == "South America") %>% nrow()` especies



